import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProviders } from "./providers";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});


export const metadata = {
  title: "Web Applications",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth" data-theme="light">
      <body className={`${PoppinsFont.variable} antialiased`}>
        <AuthProviders>
          {children}
        </AuthProviders>
      </body>
    </html>
  );
}
